### ISSUE TITLE
Different map

### ISSUE THREAD

**Issue by leolux** [mustaine/vertx3-ping-pong#1]
Why did you change the map name from "__vertx.subs" to "subs"?

Is that required for the example configuration in /dev?

**Comment by jsalinaspolo** [comment]
Not it doesn't, it is just copied from hazlecast documentation and overwrited the parts needed. 
But probably using "__vertx.subs" does the same.

**Comment by leolux** [comment]
Thanks! 

I can confirm that it also works with "__vertx.subs"

**Comment by jsalinaspolo** [comment]
I am happy that this repo is helping to someone ;)
